### ISSUE TITLE
egg项目中 安装报错   运行不了 

### ISSUE THREAD

**Issue by ywanhzy** [hollton/image-pdf#1]
npm install image-pdf  --save
npm WARN deprecated fsevents@1.0.14: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> fsevents@1.0.14 install /Users/liumu/VueProjects/egg-ywanhzy/node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/Users/liumu/VueProjects/egg-ywanhzy/node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.29
node-pre-gyp info using node@10.13.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/liumu/VueProjects/egg-ywanhzy/node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" (not found)
node-pre-gyp http GET https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Pre-built binary not available for your system, looked for https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download: https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
node-pre-gyp verb command build [ 'rebuild' ]
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h../fsevents.cc::190:
6:
In file included from ../../../../nan/nan.h:190:
../../../../nan/nan_maybe_43_inl.h:88:15: error: no member named../../../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:196:
In file included from ../../../../nan/nan_new.h:189:
../../../../nan/nan_implementation_12_inl.h:345:28: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
In file included from ../fsevents.cc:6:
In file included from ../../../../nan/nan.h:196:
In file included from ../../../../nan/nan_new.h:189:
../../../../nan/nan_implementation_12_inl.h:345:28: warning: 'New' is deprecated [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/liumu/.node-gyp/10.13.0/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/liumu/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
/Users/liumu/.node-gyp/10.13.0/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/liumu/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../fsevents.cc:6:
../../../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/liumu/.node-gyp/10.13.0/include/node/node.h:175:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/liumu/.node-gyp/10.13.0/include/node/node.h:91:20:In file included from ../fsevents.cc:6:
../../../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/liumu/.node-gyp/10.13.0/include/node/node.h:175:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/liumu/.node-gyp/10.13.0/include/node/node.h: 91:20: note: note: expandedexpanded  fromfrom  macromacro  'NODE_DEPRECATED''NODE_DEPRECATED'

    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../../../../nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/liumu/.node-gyp/10.13.0/include/node/node.h:168:1: note: 'MakeCallback' has been explicitly marked deprecated here
    __attribute__((deprecated(message))) declarator
                   ^
NODE_DEPRECATED("Use MakeCallback(..., async_context)",

**Comment by hollton** [comment]
> npm install image-pdf --save
> npm WARN deprecated fsevents@1.0.14: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> 
> > fsevents@1.0.14 install /Users/liumu/VueProjects/egg-ywanhzy/node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp verb cli [ '/usr/local/bin/node',
> node-pre-gyp verb cli '/Users/liumu/VueProjects/egg-ywanhzy/node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
> node-pre-gyp verb cli 'install',
> node-pre-gyp verb cli '--fallback-to-build' ]
> node-pre-gyp info using node-pre-gyp@0.6.29
> node-pre-gyp info using node@10.13.0 | darwin | x64
> node-pre-gyp verb command install []
> node-pre-gyp info check checked for "/Users/liumu/VueProjects/egg-ywanhzy/node_modules/react-scripts/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" (not found)
> node-pre-gyp http GET https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz
> node-pre-gyp http 404 https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz
> node-pre-gyp ERR! Tried to download: https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp)
> node-pre-gyp http Pre-built binary not available for your system, looked for https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz
> node-pre-gyp verb command build [ 'rebuild' ]
> node-pre-gyp ERR! Tried to download: https://npm.taobao.org/mirrors/fsevents/v1.0.14/fse-v1.0.14-node-v64-darwin-x64.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@10.13.0 (node-v64 ABI) (falling back to source compile with node-gyp)
> node-pre-gyp http Connection closed while downloading tarball file
> node-pre-gyp verb command build [ 'rebuild' ]
> SOLINK_MODULE(target) Release/.node
> SOLINK_MODULE(target) Release/.node
> CXX(target) Release/obj.target/fse/fsevents.o
> CXX(target) Release/obj.target/fse/fsevents.o
> In file included from In file included from ../fsevents.cc:6:
> In file included from ../../../../nan/nan.h../fsevents.cc::190:
> 6:
> In file included from ../../../../nan/nan.h:190:
> ../../../../nan/nan_maybe_43_inl.h:88:15: error: no member named../../../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
> return obj->ForceSet(GetCurrentContext(), key, value, attribs);
> ~~~ ^
> 'ForceSet' in 'v8::Object'
> return obj->ForceSet(GetCurrentContext(), key, value, attribs);
> ~~~ ^
> In file included from ../fsevents.cc:6:
> In file included from ../../../../nan/nan.h:196:
> In file included from ../../../../nan/nan_new.h:189:
> ../../../../nan/nan_implementation_12_inl.h:345:28: warning: 'New' is deprecated [-Wdeprecated-declarations]
> return v8::StringObject::New(value).Asv8::StringObject();
> ^
> In file included from ../fsevents.cc:6:
> In file included from ../../../../nan/nan.h:196:
> In file included from ../../../../nan/nan_new.h:189:
> ../../../../nan/nan_implementation_12_inl.h:345:28: warning: 'New' is deprecated [-Wdeprecated-declarations]
> return v8::StringObject::New(value).Asv8::StringObject();
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
> V8_DEPRECATED("Use Isolate* version",
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
> declarator **attribute**((deprecated))
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/v8.h:5052:3: note: 'New' has been explicitly marked deprecated here
> V8_DEPRECATED("Use Isolate* version",
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
> declarator **attribute**((deprecated))
> ^
> In file included from ../fsevents.cc:6:
> ../../../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
> return node::MakeCallback(
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/node.h:175:1: note: 'MakeCallback' has been explicitly marked deprecated here
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/node.h:91:20:In file included from ../fsevents.cc:6:
> ../../../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
> return node::MakeCallback(
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/node.h:175:1: note: 'MakeCallback' has been explicitly marked deprecated here
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/node.h: 91:20: note: note: expandedexpanded fromfrom macromacro 'NODE_DEPRECATED''NODE_DEPRECATED'
> 
> ```
> __attribute__((deprecated(message))) declarator
>                ^
> ```
> 
> In file included from ../fsevents.cc:6:
> ../../../../nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
> return node::MakeCallback(
> ^
> /Users/liumu/.node-gyp/10.13.0/include/node/node.h:168:1: note: 'MakeCallback' has been explicitly marked deprecated here
> **attribute**((deprecated(message))) declarator
> ^
> NODE_DEPRECATED("Use MakeCallback(..., async_context)",

egg、npm 以及 node版本是多少，我尝试了可以安装
